// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olkwiqngasfwezfnfimt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sa3dpcW5nYXNmd2V6Zm5maW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTMxMTQsImV4cCI6MjA2ODQyOTExNH0.b1n2a14IYfBQcbtlYbjAYtWfIF1Mxy5PtZylDiFQmYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});